services:
  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core:latest
    ports:
      - "1080:1080"
      - "8080:8080"
    secrets:
      - source: v2ray_config
        target: /run/secrets/v2ray_config.json
    command: "run -c /run/secrets/v2ray_config.json"
    restart: always

  dnsproxy:
    container_name: dnsproxy
    image: adguard/dnsproxy:latest
    ports:
      - 53:53/udp
      - 53:53/tcp
    configs:
      - source: dnsproxy_config
        target: /run/configs/accelerated-domains.china.adguardhome.conf
    command:
      [
        "--listen=0.0.0.0",
        "--listen=::",
        "--port=53",
        "--upstream=vps.wolf-monster.ts.net:53",
        "--upstream=/run/configs/accelerated-domains.china.adguardhome.conf",
        "--fallback=223.5.5.5:53",
        "--fallback=223.6.6.6:53",
        "--cache",
        "--cache-optimistic",
        "--cache-size=8388608",
        "--timeout=5s",
      ]
    restart: always

  caddy:
    container_name: caddy
    image: caddy:alpine
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/srv:ro
    ports:
      - "80:80"
    command: "caddy file-server -r /srv/www"
    restart: always

volumes:
  caddy_data:
  caddy_config:

configs:
  dnsproxy_config:
    file: ../dnsmasq-china-list/accelerated-domains.china.adguardhome.conf

secrets:
  v2ray_config:
    file: ./v2ray_config.json
