services:
  dnsproxy:
    container_name: dnsproxy
    image: adguard/dnsproxy:latest
    ports:
      - 53:53/udp
      - 53:53/tcp
    configs:
      - source: dnsproxy_config
        target: /run/configs/accelerated-domains.china.adguardhome.conf
    secrets:
      - source: domain_crt
        target: /run/secrets/pi.wolf-monster.ts.net.crt
      - source: domain_key
        target: /run/secrets/pi.wolf-monster.ts.net.key
    command:
      [
        "--listen=0.0.0.0",
        "--port=53",
        "--https-port=443",
        "--http3",
        "--tls-crt=/run/secrets/pi.wolf-monster.ts.net.crt",
        "--tls-key=/run/secrets/pi.wolf-monster.ts.net.key",
        "--upstream=dns.wolf-monster.ts.net:53",
        "--upstream=/run/configs/accelerated-domains.china.adguardhome.conf",
        "--fallback=223.5.5.5:53",
        "--fallback=223.6.6.6:53",
        "--cache",
        "--cache-optimistic",
        "--cache-size=8388608",
        "--cache-min-ttl=600",
        "--cache-max-ttl=3600",
        "--timeout=300ms",
      ]
    restart: always

  caddy:
    container_name: caddy
    image: caddy:alpine
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/srv:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    ports:
      - "80:80"
      - "443:443"
    command: "caddy run --config /srv/Caddyfile"
    restart: always

volumes:
  caddy_data:
  caddy_config:

configs:
  dnsproxy_config:
    file: ../dnsmasq-china-list/accelerated-domains.china.adguardhome.conf

secrets:
  domain_crt:
    file: ./certs/pi.wolf-monster.ts.net.crt
  domain_key:
    file: ./certs/pi.wolf-monster.ts.net.key
