version: "3"

services:
  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core:latest
    ports:
      - "1080:1080"
      - "8080:8080"
    secrets:
      - v2ray_config.json
    command: "run -c /run/secrets/v2ray_config.json"
    restart: always

secrets:
  v2ray_config.json:
    file: ./v2ray_config.json
