services:
  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core:latest
    ports:
      - "1080:1080"
      - "8080:8080"
    secrets:
      - v2ray_config.json
    command: "run -c /run/secrets/v2ray_config.json"
    restart: always

  caddy:
    container_name: caddy
    image: caddy:alpine
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/srv:ro
    ports:
      - "80:80"
    command: "caddy file-server -r /srv/www"
    restart: always

volumes:
  caddy_data:
  caddy_config:

secrets:
  v2ray_config.json:
    file: ./v2ray_config.json
