version: "3"

services:
  caddy:
    container_name: caddy
    image: caddy:alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
    restart: always

  owncast:
    container_name: owncast
    image: owncast/owncast:latest
    volumes:
      - owncast_data:/app/data
    ports:
      - "1935:1935"
    restart: always

  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core:latest
    ports:
      - "1080:1080"
      - "8080:8080"
    secrets:
      - v2ray_config
    command: ["run", "-c", "/run/secrets/v2ray_config"]
    restart: always

volumes:
  caddy_data:
  owncast_data:

secrets:
  v2ray_config:
    file: ./v2ray_config.json
